techpack:display: fix type specifier missing
../techpack/display/msm/sde/sde_hw_dsc_1_2.c:80:15: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
static inline _dsc_subblk_offset(struct sde_hw_dsc *hw_dsc, int s_id,
~~~~~~~~~~~~~ ^
int
1 error generated.

Signed-off-by: klozz <carlosj@klozz.dev>